# Generated by Django 3.0.5 on 2020-04-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200409_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='proprietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Pessoa'),
        ),
    ]
